//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeLevel.Client.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Citys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Citys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeLevel.Client.Web.Resources.Citys", typeof(Citys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adana.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artvin.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aydın.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balıkesir.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bartın.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batman.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayburt.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilecik.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingöl.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitlis.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolu.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adıyaman.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burdur.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bursa.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çanakkale.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çankırı.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çorum.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denizli.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diyarbakır.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzce.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edirne.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elazığ.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afyon.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzincan.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erzurum.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eskişehir.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaziantep.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giresun.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gümüşhane.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkari.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatay.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iğdır.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isparta.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ağrı.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstanbul.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzmir.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.maraş.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karabük.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karaman.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kars.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kastamonu.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayseri.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilis.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kırıkkale.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aksaray.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kırklareli.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kırşehir.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kocaeli.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konya.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kütahya.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malatya.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manisa.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mardin.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mersin.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muğla.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amasya.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muş.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nevşehir.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niğde.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordu.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osmaniye.
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rize.
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya.
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsun.
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şanlıurfa.
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siirt.
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankara.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinop.
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şırnak.
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sivas.
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekirdağ.
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokat.
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabzon.
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunceli.
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uşak.
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van.
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yalova.
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antalya.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yozgat.
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonguldak.
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ardahan.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
