//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeLevel.Client.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeLevel.Client.Web.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih formatı hatalı !! (gün/ay/yıl formatında olmalı).
        /// </summary>
        internal static string Error_DateFormat {
            get {
                return ResourceManager.GetString("Error_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta adresi hatalı !.
        /// </summary>
        internal static string Error_EmailMessage {
            get {
                return ResourceManager.GetString("Error_EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eposta gönderilemiyor !! Hizmet aldığınız eposta sunucusunda anlık bir sorun olabilir veya göndermeye çalıştığınız eposta adresi geçerli olmayabilir. Bazı durumlarda aşağıdaki hata ayrıntısından sorunun ne olduğu anlaşılabilir. Atmaya çalıştığınız eposta adresinin doğruluğundan eminseniz  ve bu hatayı sürekli alıyorsanız hizmet aldığınız eposta hizmetinin yıllık ücret süresi dolmuş olabilir, bu durumda eposta sunucu şirketi ile iletişime geçiniz.  Hata ayrıntısı --&gt; .
        /// </summary>
        internal static string Error_MailCanNotSend {
            get {
                return ResourceManager.GetString("Error_MailCanNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifre minumum 6 haneli, en az 1 harf ve 1 rakam içermelidir !!.
        /// </summary>
        internal static string Error_Password {
            get {
                return ResourceManager.GetString("Error_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir$j7k#hT6/20nH]Ht43=Ku8.
        /// </summary>
        internal static string PassKey {
            get {
                return ResourceManager.GetString("PassKey", resourceCulture);
            }
        }
    }
}
